env:
- REPORT_CARD_GITHUB_STATUS_TOKEN=$$report_card_github_status_token
- REPORT_CARD_GITHUB_REPO_TOKEN=$$report_card_github_repo_token
image: node0.10
publish:
  npm:
    email: $$npm_drone_email
    password: $$npm_drone_password
    registry: https://registry.npmjs.org
    username: $$npm_drone_username
    when:
      branch: master
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
script:
- sudo pip install -q git+https://$REPORT_CARD_GITHUB_REPO_TOKEN@github.com/Clever/report-card.git; GITHUB_API_TOKEN=$REPORT_CARD_GITHUB_STATUS_TOKEN report-card --publish || true
- nvm install 0.10.29
- npm install npm@2.7.0 -g
- npm install
- npm test
- ./setup_docker.sh
- ./publish_nodejitsu.sh .
