image: node:0.10.39
publish:
  npm:
    email: $$npm_drone_email
    password: $$npm_drone_password
    username: $$npm_drone_username
    when:
      branch: master
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
script:
- ./publish_npm.sh
- npm install
- npm test
